image: node:9-stretch

before_script:
  - node --version
  - npm --version
  - npm install
  - apt-get update -qq && apt-get install -y -qq ncftp zip sed
  - sed -i 's#http://localhost:28113#https://pic4review.pavie.info/devapi#' src/app/constants.js

cache:
  paths:
    - node_modules/

test:
  script:
    - npm run doc:js:check
    - npm run test

deploy:client:develop:
  stage: deploy
  only:
    - develop
  script:
    - npm run build
    - ncftpput -u $FTP_USER -p $FTP_PASS -R $FTP_HOST $FTP_FOLDER/dev/ ./build/*
    - ncftpput -u $FTP_USER -p $FTP_PASS -R $FTP_HOST $FTP_FOLDER/builds/ ./Pic4Review_latest.zip

deploy:client:tags:
  stage: deploy
  only:
    - tags
  script:
    - sed -i "s#https://pic4review.pavie.info/devapi#https://pic4review.pavie.info/api#" src/app/constants.js
    - sed -i "s#KHkPq0Llu63IWjdchiKALkAcDfJUwqi6GHKM9IY6#${OAUTH_CONSUMER_KEY}#" src/app/constants.js
    - sed -i "s#PWXMH1Ko6vOFFI69wvwv2p9yH8y5Af2cJ8nMkXf0#${OAUTH_SECRET}#" src/app/constants.js
    - npm run build
    - ncftpput -u $FTP_USER -p $FTP_PASS -R $FTP_HOST $FTP_FOLDER/ ./build/*
    - ncftpput -u $FTP_USER -p $FTP_PASS -R $FTP_HOST $FTP_FOLDER/builds/ ./Pic4Review_latest.zip
    - mv ./Pic4Review_latest.zip ./Pic4Review_$(git tag -l --points-at HEAD).zip
    - ncftpput -u $FTP_USER -p $FTP_PASS -R $FTP_HOST $FTP_FOLDER/builds/ ./Pic4Review_$(git tag -l --points-at HEAD).zip
    - npm run doc
    - ncftpput -u $FTP_USER -p $FTP_PASS -R $FTP_HOST $FTP_FOLDER/doc/ ./doc/*
